### ISSUE TITLE
Allow removing "summary" role on accounts without postings

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1009]
When one saves an account, it's not possible to remove the summary role if you selected one and you want to immediately remove it (because added in error).

**Comment by einhverfr** [comment]
I don't think this is limited to accounts without postings.  The only reason we require this distinction is that you can't have both roles in the same transaction due to our current db structure.

But there are legitimate cases where having that would be a good idea (think of reserves in credit card processing vs client payables accounts).  So long run i want to get rid of the rule that you cannot be a summary account and have other links.

So with that in mind, I think we can have this be removable for all accounts and not worry whether or not they have postings.

Now we *do* need to worry about whether they are tied to parts, customers, vendors, etc. though.

**Comment by einhverfr** [comment]
General plan is to correct this when the gl rewrite goes out.

**Comment by ehuelsmann** [comment]
I don't see the relation between the financial rewrite and the optional removal of this flag. Let's enable this when we can (which is any time, even before the rewrite).

**Comment by ehuelsmann** [comment]
This has been taken care of by #5113: the drop-down now has an empty value which can be selected, not just an empty initialization.
