### ISSUE TITLE
Account balances incorrect when starting in the middle

### ISSUE THREAD

**Issue by msdeason** [ledgersmb/LedgerSMB#1259]
Recently upgrade from 1.4.20 to 1.4.22.  Database was created in 1.4.20.  This problem was persistent across the upgrade.

Choosing my checking account from chart of accounts from the beginning produces the correct running balance (without regard to sign -- when the balance checkbox is chosen), however starting from a more recent date does not...

Entire account...
![image](https://cloud.githubusercontent.com/assets/13155320/12271265/0cd737ee-b90f-11e5-9b82-b46b89b8d881.png)

from 2016-1-1...
![image](https://cloud.githubusercontent.com/assets/13155320/12271336/4c40203a-b90f-11e5-879a-2a26e71cce44.png)

**Comment by ehuelsmann** [comment]
@msdeason Thanks for the report! Yesterday we released 1.4.23; it should be fixed there. Please check and let me know if it does indeed!

The problem was that the data of the start-date of the report was double-counted in the running balance. If you run your report from 2015-12-30, you should get the correct balances (assuming there are no postings on that date).

I'll close now, assuming your verification turns out positive, but please re-open if the problem persists!

**Comment by ehuelsmann** [comment]
Closing.

**Comment by msdeason** [comment]
Fix confirmed... thx for the quick response!
