### ISSUE TITLE
Use of uninitialized value in substitution (s///) at lib/LedgerSMB/Scripts/user.pm line 98.

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#1695]
This error occurs every time a user changes their password.
It appears that it's caused by the dateformat not being set before this time.
- We should ensure the dateformat is ALWAYS correctly set when a user logs in.
- Also we should ensure the Language is correctly set as well. It currently defaults to the first entry in the listbox

**Comment by einhverfr** [comment]
If we want to discuss defaults for dateformat and language we probalby want anoother needs-design ticket for these.  My thinking is that defaults for users should be configurable per system (perhaps defaulting to en for language and yyyy-mm-dd for date format, just because that is neutral and less likely to cause data entry errors).

However, our password changing right now is done in a way that doesn't even reload the page, so there is no point to this substitution.  So I will silence this error.  Will close this ticket when that is done, in the interest of one issue per ticket.
