### ISSUE TITLE
Fix user-interface related handling of roles for reconciliation

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#1715]
The current Reconciliation module only protects deletes, not approves or rejects.
It also relies on role checking which isn't allowed for a package with LedgerSMB 1.3 architecture.
Either put the access checks in the database or complete porting this portion to 1.5 with Moose.

**Comment by einhverfr** [comment]
I just checked again.  What makes you think that this is not protected?  And are you checking with a non-db-user?

I just checked the Roles.sql file again and we are using db controls here.

See sql/modules/Roles.sql lines 628-652

**Comment by ehuelsmann** [comment]
@einhverfr he's referring to:

https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/DBObject/Reconciliation.pm#L226

versus

https://github.com/ledgersmb/LedgerSMB/blob/master/lib/LedgerSMB/DBObject/Reconciliation.pm#L165

*and* the fact that the code in the former link doesn't work, because $self is a PGOld while "is_allowed_role" is in LedgerSMB.pm (not in PGOld).

**Comment by einhverfr** [comment]
Ok then.  This should be fixed.  the key thing is that these checks are there to enable/disable buttons only. The hard checks are actually on the db side.  So with that note, will tag this as a UI bug.

**Comment by einhverfr** [comment]
ok so the side effect of the current fix is that users without reconciliation permission will no longer be able to delete their own reports.  This could bite us elsewhere as well especially since we don't use this code in a lot of places.

Recommend we add a new is_allowed_role function which calls this dynamically when asked.
