### ISSUE TITLE
1.5:  Parts selection confusing 

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1758]
Discussed in person by Kaare.

The current behavior is that you can search on the partnumber in the partnumber field.  You can still search for the description in the description field and update.  However this is a bit confusing for new users.  It would be much better if we could search under both fields in the partnumber field and still do the full text search in description.

**Comment by ehuelsmann** [comment]
@einhverfr hmm. that's not how it's supposed to work: the parts number search should allow searching for the part number *or* the description. The description has become without search function, if I'm correct. If that's *not* the case, then I think we have a problem, because the function to search/list parts in the Perl backend has gone.

**Comment by einhverfr** [comment]
hmmm then we have a prblem.  the search still works when a singe part is returned...

**Comment by einhverfr** [comment]
fixed with Erik's commits.
