### ISSUE TITLE
Qty discounts via pricematrix

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#1790]
It would be nice to be able to specify bulk pricing via the pricematrix.

There are a number of problematic corner cases here.  These include:

1.  Do all have to be on the same line?
2.  If a lower price is found, do we re-calculate, possibly overriding something manually entered?

**Comment by kaare** [comment]
I find this most natural

1. no
2. Only if the quantity price is lower

But at least 2. could be very installation specific (perhaps even finer grained). So how about controlling this with some config options? - like

1. Option is yes/no (or true false)
2. Option is always/never/lower only/ask

or something like that

**Comment by einhverfr** [comment]
ok so here is my proposed design then:

1.  On new item line we *always* check accumulated qty and override previous lines if the price is lower on all previous prices.

2.  If a qty is edited, we include which lines we are rechecking here as well.

Rule is lowest applicable price applies.

Does this sound sane?

**Comment by JigmeDatse** [comment]
From a customer standpoint, certainly lowest price is preferable.  I think from a business practices perspective, it is as well.  But some businesses might prefer a different behaviour.  I think that if we manage to get this to work this way, and end up getting asked for a different behaviour to remember when someone suggests a different behaviour to treat it most often as an "option" rather than a "replacement".  

I use a piece of software which would keep changing how it sorted things, and which there was no real way to select the sort, and I decided to offer the feedback that this constant changing was rather frustrating.  The response I got back was "How would you like it sorted?" which failed to address *my* concern that it kept changing.  I don't *mind* the use of different behaviours, or even changing defaults.  But changing default behaviour, without leaving an option to revert to previous default behaviour becomes very annoying if it keeps happening.

**Comment by einhverfr** [comment]
Agree on the question of stability questions.  My view is that:
1.  The most common use cases should be the default
2.  Other use cases should be plugins or options.

The current logic in the price matrix is lowest applicable price.  This makes things nice and predictable.  The difficulty here is that for the first time, we are introducing the possibility of setting up a price matrix that would change previous lines (not just most recent) and so I think it is important to get the requirements right the first time so we dont disrupt other people's approaches.

Sorting things generally is something that when it changes can be an annoyance.  However, as you can imagine, if we changed the pricing logic in such a way, that would be far more disruptive....

**Comment by einhverfr** [comment]
I was incorrect abotu one thing above, namely that we currently sort on price.

We currently sort on specificity, which is a little more complex in this case.    I am leaving the specificity ordering in place but think in future versions we ought to be able to give a configurable sort order

**Comment by einhverfr** [comment]
expect to get this in today :-)
