### ISSUE TITLE
1.5 TODO Schema changes

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#1959]
These TODO's in our sources need to be reviewed:

```
t/01-load.t:     #@@@TODO: 1.5 release blocker!
```

```
sql/Pg-database.sql:--TODO 1.5 invoice_id references invoice(id)
sql/Pg-database.sql:--TODO 1.5 ap invnumber text check (invnumber ~ '[[:alnum:]_]') NOT NULL
sql/Pg-database.sql:--TODO 1.5 ap paid,datepaid , drop those fields? they are not maintained in Payment.sql!
```

```
sql/modules/Company.sql:--TODO 1.5 in_id not used in function,drop it
sql/modules/Payment.sql:--TODO 1.5 parameter in_cash_approved not used in function, use it or drop it?
```

**Comment by ehuelsmann** [comment]
Note: the above have been found by searching for TODO and 1.3/1.4/1.5 on the same line. There are no TODO 1.4 and 1.3 items in the search results. (Although I'm not sure there aren't any...)

**Comment by einhverfr** [comment]
expect to review this shortly.

**Comment by einhverfr** [comment]
The invoice_id seems to be safe to do afaics.  Leaving the AP changes for 1.6 so they don't pose unvetted migration problems.   If people have trouble migrating because of old data we may have to adjust something however.

Removed the company id field from the function.
I really don't want to touch the single payment interface to remove that field.  I think any change there is going to require a level of manual testing I would just as soon punt to at least 1.6
