### ISSUE TITLE
cannot print documents twice with new print button

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2083]
Second time, nothing happens..

Expect this to be fixed before ga.

**Comment by freelock** [comment]
This appears to have regressed in 1.5.0... re-opening

**Comment by freelock** [comment]
You can print to screen 1x, and after that the print button doesn't work, even if you navigate to other orders, invoices, etc.

Print button is dead until you reload the whole browser.

**Comment by freelock** [comment]
reproduced in both current Chromium and Firefox.

**Comment by freelock** [comment]
... this appears to be a quoting issue in the request-download cookies. From the Firefox developer tools, here is the raw set of cookies being passed by the request (with all other cookies omitted):

"request-download.1483467657961=requested; "request-download.1483467657961"="downloaded"; request-download.1483469563345=requested; "request-download.1483469563345"="downloaded"; request-download.1483471976577=requested; "request-download.1483471976577"="downloaded"; request-download.1483472438698=requested; "request-download.1483472438698"="downloaded"; request-download.1483480667037=requested; "request-download.1483480667037"="downloaded"; request-download.1483481476367=requested"

... it appears that the request passes a cookie `Cookie: request-download.1483467657961=requested` and gets back a quoted response, `SetCookie: "request-download.1483467657961"="downloaded"`

... so the browser does not match up the cookie, because the new cookie name is quoted.
