### ISSUE TITLE
Payment counted twice

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2112]
(Related to #2111)

After having received the money, it's totaled twice (meainging, there's one line, but the amount is twice as big as the received money) in this report: Cash -> Report -> Receipts. Also, there's a 'Date Paid' colum, which is empty.

The actual payment seems OK, both when looking at the invoice, and in the report General Journal -> Search and GL, listing the bank account. The only problem there is that there is an extra line, but with 0.00 in Credits (the actual payment is in Debits). And still, there is no date in the Date column.

**Comment by ehuelsmann** [comment]
The problem here is that the payment has been inserted into the payments table, just hasn't been assigned a payment date.
so, your payment probably *is* duplicated. Researching more what's going on here.

**Comment by ehuelsmann** [comment]
There are 2 bugs here:

1. There's a regression in the payment entry screen which prevents "today" showing as the proposed payment date
2. Due to the date not having been proposed *and* not having been entered by the user, we're creating a "date-less" payment (payment with `transdate` == `NULL` value)

The first bug I will resolve right now. The second bug (missing NOT NULL restriction) can't be resolved at the moment due to the fact that 'old code' knowingly inserts NULL values and only after that replaces the values in an UPDATE statement. We want to migrate away from that ASAP -- code already has been replaced on master-mc while I was at it.

**Comment by ehuelsmann** [comment]
@kaare your payment has been inserted into the database twice. I think it's probably best to talk to Chris on Monday how to resolve this. I'm thinking the most reliable way to resolve things is to set the missing date values (in the `payment` and `acc_trans` tables) and revert one of the two payments.
