### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by yarir** [ledgersmb/LedgerSMB#2165]
$LSMBHOME/README.md

A more comprehensive list of dependencies, and split by modules vs. binaries, would be good (perhaps in another file).

"--with-feature" is an experimental feature, Perl has some very old experimental features.  Can two features conflict?  Are results defined if re-run with differing features?  The Perl5 team probably did a fine job, so this is probably a marketing issue.

'createuser --no-superuser --createdb --login --createrole --pwprompt lsmb_dbadmin'

should be

'createuser --no-superuser --createdb --login --createrole --pwprompt lsmb_admin'
                                                                                                                        
to match pg_hba.conf contents.

If there is not to be a shell login for lsmb_admin that might be clarified for the naive.

**Comment by ehuelsmann** [comment]
@yarir thanks for filing these improvements and enhancement ideas.

We list all the immediate dependencies, not included in the minimum Perl distribution (5.10 at the moment). Our reasoning not to include the list of "dependencies of dependencies" is because such a list might change at any time due to the fact that our dependencies may include new requirements in new releases. As such, it's extremely hard to keep such a comprehensive list up to date (and thus relevant).
Could you explain what you think to get out of the "more comprehensive list of dependencies"? 

You mention that `--with-feature` is experimental. That's true, but I'm not sure it's relevant to the installation instructions for recent LedgerSMB releases: the feature is there and working (at least for us: we use it every day in our Continuous Integration builds).
We have 2 experimental features ourselves, by which we mean "use at your own discretion, or better not use it if you don't know what you're doing".
As to conflicting features: we haven't listed any conflicting features because there aren't any in the features we support today. Maybe in the future there will; at that time, we'll include that in the discussion of the features in the list. I'm not sure what you mean about "marketing" in this context.

Thanks for the heads-up on the admin user creation instruction. Instead of changing the user creation, I've changed the pg_hba.conf, because the name lsmb_dbadmin was chosen quite deliberately -- to make the distinction between the database admin user and an application level admin which will be introduced later in the documentation.

**Comment by yarir** [comment]
On Wed, Sep 28, 2016 at 01:42:09PM -0700, Erik Huelsmann wrote:
> We list all the immediate dependencies, not included in the minimum Perl 
> distribution (5.10 at the moment). Our reasoning not to include the list 
> of "dependencies of dependencies" is because such a list might change at 
> any time due to the fact that our dependencies may include new requirements 
> in new releases. As such, it's extremely hard to keep such a comprehensive 
> list up to date (and thus relevant).

> Could you explain what you think to get out of the "more comprehensive 
> list of dependencies"? 

Good point.  I would prefer to keep my Debian system a Debian system so
much as possible--that requires avoiding _needlessly_ loading CPAN
modules.  

The mixing of binaries and libraries together in one list is not helpful.



> You mention that `--with-feature` is experimental. That's true, but I'm not 
> sure it's relevant to the installation instructions for recent LedgerSMB 

I agree that it is not important for beta software.

> We have 2 experimental features ourselves, by which we mean "use at your own 
> discretion, or better not use it if you don't know what you're doing".

The difference is that the user doesn't have any other option with the 
'cpanm' option.   On the technical level, the '--with-feature' feature is 
poorly documented for those who don't know what cpan is.

> As to conflicting features: we haven't listed any conflicting features 

The user doesn't know that.  I guessed that and knowing cpan(1) I 
was confident that cpanm would accumulate the effects of '--with-feature', 
but I have been using Perl for over two decades.

The marketing aspect is more important, that some people will reject
software out of hand for being experimental.

Thanks again.

Rob
-- 
Robert Ransbottom
General Supply and Metals, Inc.
47 Nauset St.
New Bedford, MA  02746-1515
PH. 508-999-6257
FX. 508-992-8172

**Comment by ehuelsmann** [comment]
We list all the immediate dependencies, not included in the minimum Perl
 >>  distribution (5.10 at the moment). Our reasoning not to include the list 
 >>  of "dependencies of dependencies" is because such a list might change at
 >>  any time due to the fact that our dependencies may include new requirements
 >>  in new releases. As such, it's extremely hard to keep such a comprehensive
 >>  list up to date (and thus relevant).
 >>  Could you explain what you think to get out of the "more comprehensive
 >>  list of dependencies"?

 > Good point.  I would prefer to keep my Debian system a Debian system so
 > much as possible--that requires avoiding _needlessly_ loading CPAN 
 > modules.

The [Perl dependencies paragraph](https://github.com/ledgersmb/LedgerSMB#perl-module-dependencies) ends with a sentence pointing users to the in-depth installation instructions which lists all distro packages as far as they're currently known to us. So, your use-case is completely supported by our documentation. However, I appreciate you couldn't find that sentence. Where do you think you would have found it?

>> We have 2 experimental features ourselves, by which we mean "use at your own
>> discretion, or better not use it if you don't know what you're doing".

>The difference is that the user doesn't have any other option with the
>'cpanm' option.   On the technical level, the '--with-feature' feature is
>poorly documented for those who don't know what cpan is.

True. However, since the scope of the README is to be a "Quick installation guide" (with reference to the "in-depth installation instructions"), I'm hesitant to put more instructions in the README. I'd be happy to extend the in-depth instructions or put references to using `cpan` / `cpanm` in the [in-depth document](http://ledgersmb.org/topic/installing-ledgersmb-15). Do you have a suggestion what to link to and where to put it in the "flow" of that document?

> The marketing aspect is more important, that some people will reject software out of hand for being experimental.

For our own experimental features, that's exactly the point: we don't want anybody using those who isn't prepared to take some pain. Personally, I have never disqualified a program for having an experimental feature. I *have* refrained from using those features when they were labelled as such on software that I was using in production.

The current listing hopes to achieve the effects similar mentions had for me (in other projects), with the users of LedgerSMB: to help them make informed decisions. Is your point that we should not have mentioned the features (until they are mature; but then, how do they get mature if they don't get any real-world use)? Or we should not mark them as experimental?
