### ISSUE TITLE
Forbid out-of-order reconciliation approval

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2255]
Reconciliation submits and approvals are separated.

Although in normal situations, they should follow each other closely, nothing prevent anyone from batching them adn, with separation of duties, have a significant delay between submittal and approval. Approval cannot be reversed.

Nothing forbid approving the latest but not a previous one.
If this is allowed, one could refuse a previously submitted reconciliation, change it, submit a new one, approve it and end up with a non-valid, uncorrectable previously approved reconciliation.

Out of order reconciliations approval should be forbidden.

**Comment by ehuelsmann** [comment]
While this is not an accounting bug, it's definitely an enhancement/bug which will improve the accounting controls (accounting bug means incorrect accounting while incorrect controls don't necessarily mean incorrect outcomes of the accounting process).

**Comment by ehuelsmann** [comment]
@ylavoie how should this work exactly? Should it work like this:

* If there is a submitted earlier reconciliation, then the recon can't be approved
* If there is a later approved reconciliation then the current one can't be submitted

**Comment by ylavoie** [comment]
We should never allow submitting many reports for the same period, only the latest can be approved or rejected and the duplicates will stay forever.
So either:
- we allow edition on a submitted recon before approval or rejection
- we require rejection to allow submission of a new one.

**Comment by ehuelsmann** [comment]
@ylavoie I've been contemplating your answer, but i don't understand your remark about multiple reports for the same period: our reports only have an end date, not a start date, so any later date will necessarily overlap. This would mean to disallow more than one submitted report?

I'm also not sure about duplicates which stay forever. Any non-approved recon can be deleted.

One thing that changed with the merge this morning is that no two submitted reconciliations can contain the same transaction. Does that change what to do in this issue?

**Comment by ehuelsmann** [comment]
Closing. It's no longer viable to do as you described. I tested the following:

3 transactions on 3 consecutive days (2023-01-01, -02 and -03); each moving 1$ into checking account from petty cash.

Then, I reconciled Jan 01, submitted and approved.
Then, I reconciled Jan 02, submitted but didn't approve.
Then, I started reconciliation of Jan 03. The "Starting balance" was 1$, because the last reconciliation approved was Jan 01.  By just reconciling Jan 03, the starting balance and the reconciled amount don't add up to the ending balance. Hence, there's no option to approve the Jan 03 reconciliation.

For completeness, I saved the Jan03 recon; went back to the Jan 02 recon and approved. Then went back to the Jan 03 recon. From here, it was now possible to submit and approve.

I guess this issue does not exist (anymore).
