### ISSUE TITLE
Reconciliations report deletion

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#2345]
Transactions are marked cleared on reconciliation report submit.
They need to be uncleared if a report is rejected and then deleted or they will stay cleared indefinetely.

**Comment by ehuelsmann** [comment]
Ideally, we don't clear the transactions but the report.
Then, when determining cleared status, we need to look at the transaction *or* the report. If either is cleared, so is the transaction. Then, when we delete the report, the transactions automatically become "uncleared".

**Comment by ehuelsmann** [comment]
Looking at the actual code, I don't understand the problem here: The `cleared` state in the cr_report_line table is  set when saving and submitting. It *isn't* copied to the acc_trans table until a reconciliation report has been approved. (See https://github.com/ledgersmb/LedgerSMB/blob/041b2c0a990995dde5a42601da7ba8d099ce1306/sql/modules/Reconciliation.sql#L224)

The above means that when a report is deleted (not possible after it's been approved), no permanent state remains: the report and its report lines (with the cleared states) are deleted from the reconciliation reports tables.

@ylavoie could you provide more detail as to the symptoms you have whitnessed?

**Comment by einhverfr** [comment]
Agreed.  I don\t see a problem here.  It is ony on approval that the acc_trans cleared stuff gets updated.  If that's not the way it works then we have a problem.

**Comment by einhverfr** [comment]
Note that the cleared field in cr_report_line means "cleared in this report" while in acc_trans it means "cleared in an approved report"

These are independent.  One can be cleared in one place and not in the other.
