### ISSUE TITLE
Change checkmark behaviour in single payment screen

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#2432]
*Every* new user uses the POST button on the single payment screen and accidentally posts *all* outstanding transactions instead of the selected one(s).

We really should change the meaning of the checkmark to be INCLUSIVE instead of EXCLUSIVE, or introduce an intermediate step showing the payment transaction that will be created.

IMO, this is a very high priority issue, being discussed on the users mailing list for *years*: http://archive.ledgersmb.org/ledger-smb-users/msg08679.html

**Comment by nick-prater** [comment]
Yes please! +1 from me.
For one of my customers I typically have 20 open invoices, however they pay each separately. So on the payment screen that means I have to select the 19 they're not paying rather than the 1 that they are. The select-all button helps, but I find the current behaviour counter-intuitive.
