### ISSUE TITLE
Adjust db admin user on clone or restore

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#2538]
As we have changed the default db admin user from ledgersmb to lsmb_dbadmin to help users distinguish what username does what we need to ensure both our docs and code handle the case where a db owned by ledgersmb (or some other user) is correctly imported and upgraded

**Comment by sbts** [comment]
As @ehuelsmann raised in #ledgersmb we need to provide a user prompt with options to 
- make the change
- delay the change
- never prompt again for this db

**Comment by sbts** [comment]
from discussion with ehuelsmann [here in #ledgersmb](https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$14844792421582115kwzcN:matrix.org)
this is probably implementable along these lines.

- use a SECURITY DEFINER / (GRANT/REVOKE) / SET ROLE combination similar to what we do for creating a new user
  - "users who have been granted "admin users" get execution on a security definer function which creates a new login-role"
- Store a value within the DB to indicate 
  - never ask for this DB
  - don't ask this week
These should allow temporarily ignoring the request, or permanently ignoring
- Prompt the user if the currently authenticated admin user is different to that of the selected DB
- Add a "Change Owner" option to the setup menu once a DB is selected  

We should consider these mechanisms for making this change
- login to setup.pl
- copy/clone db
- possibly during a backup but only affecting the backup
- manually triggered from the setup ui

The user prompt (on all except manual trigger) should offer the following options
- change now
- ask again later
- never for this db

and possibly
- Never for this admin user on this db
Although with a manual trigger option it's not really needed, the never option would then serve the same in most cases

**Comment by ehuelsmann** [comment]
While I'm 100% agreed with how we currently advise users to set up their systems, I'm wondering whether we should force change on those who have been running their systems according to our original advice. It may cause more harm that good, as it probably creates confusion on upgrades.

That said, I don't think we should make a problem out of this situation. People should manage their systems. If they don't, then they don't... But I seriously doubt it's our problem to solve.

If the issue here is that we should provide users more hints on why their commands don't work, then you have a huge +1 here. But adding the complexity you describe above? I think we have bigger problems for the year(s) to come...

**Comment by ehuelsmann** [comment]
There were hardly (if any) complaints about this topic. It's taking too many cycles from the things that matter.
