### ISSUE TITLE
localization of error messages in "libraries" considered harmful

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/LedgerSMB#2566]
In throwing together a quick Dancer-based web service gateway, one of the big problems is that we localize error messages in GL.pm and other library PMs.  This means you cannot really use these libraries without a pretty heavy instantiation of the whole framework and that usually means working from the lsmb directory.

We should rip out $locale->text() calls and use warn/die instead with exception handing (and localize there).

**Comment by ehuelsmann** [comment]
Actually, I'm completely *for* solving the problems we have running as a library. I think this issue is really 2-in-1:

1. We (finally!) need to decide how to do our error handling
2. Much more code should behave as a library, which means:
   a. We need a generally used error handling strategy
   b. We need to stop using global state (App_State being an example)
   c. We need to provide ways to provide access to the calling context
   d. We need to define clear input+output promisses

I don't think these fall in the category "bug" but rather in the category "we need a *design*".

**Comment by einhverfr** [comment]
I agree with your division and if we don't have a needs-design issue for the second, we need to have one.

But as a note, there is a fairly big difference between a global state container like App_State, and depending on something which assumes we are running in a particular location.

Error handling has changed a few times and this one is my bad (I added the localization problem I think for 1.4).  And it has effects which are particularly hard to work around.

**Comment by ehuelsmann** [comment]
For reference, what problems are the translated messages causing you in particular at this point?

**Comment by einhverfr** [comment]
I think I can get a PR on this this weekend.

The problem came from the gateway I was building when it came to bringing out GL transactions.  The problem was that without a locale object, every error gets reported as an inability to call the localisation function, which is far less than helpful.  The solution I hacked together was to throw a duck-typed locale pseudo-object in App_State but really don't like that.

I expect to have a PR against master this weekend. I think that deserves an important Developer mention in the changelog since it enables third-party tools.

**Comment by ehuelsmann** [comment]
The description of the issue is indicative of a deeper architectural issue. This outside itself is just a manifestation of the fact that or code doesn't behave as a library, but instead assumes a lot about the calling context.
