### ISSUE TITLE
Linux::Inotify2: replace with a cross-platform alternative

### ISSUE THREAD

**Issue by hasorli** [ledgersmb/LedgerSMB#2637]
Linux::Inotify2 is only usable on Linux. 
At the current writing is only  used in : ./LedgerSMB/conf/systemd/plackup_ledgersmb-development.service

from : plackup_ledgersmb-development.service : 
"# Make sure that Linux::Inotify2 is included in your Perl environment, file"
"# monitoring is a performance killer otherwise."

Related case: 
[Makefile](https://github.com/ledgersmb/LedgerSMB/issues/2628) "all_dependencies" missing Test :: Trap, Excel :: Writer :: XLSX, Spreadsheet :: Write Excel

**Comment by sbts** [comment]
@hasorli 
At this time I don't know of any alternative to Inotify, definitely not a cross platform one as it's a very platform specific thing, infact it's almost filesystem specific.

That file will work just fine, even if Inotify is not installed, the --Reload option will however slow things down without it though.

Having said that, as it's a development tool only, there may be little to no need to change this in the foreseeable future.

**Comment by sbts** [comment]
Additionally as Starman doesn't support being run on Windows this is even less of an issue.

However, after some digging it turns out that Linux::Inotify2 was incorrectly added as a "requries" to cpanfile.
That has been corrected, it's now a "recommends" so shouldn't break cpanm usage on  non linux systems (we believe)
That was done in PR #2638 and this issue will be closed once it's merged
