### ISSUE TITLE
Attachments Listed twice after upgrade from 1.3 to 1.5.

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#2659]
After upgrading from 1.3.30 to 1.5.3, attached files to invoices are listed twice. Both correctly connect to the pdf file. They just appear twice.

**Comment by ehuelsmann** [comment]
The cause of this problem is here: https://github.com/ledgersmb/LedgerSMB/blob/master/sql/upgrade/1.3-1.5.sql#L626

Because the content of the `file_base` table is migrated as well as the content of the other `file_*` tables; but since the content of `file_base` *includes* all records of the other `file_*` tables, this is migrating double.

**Comment by ehuelsmann** [comment]
Fixed in 1.4.39 too.
