### ISSUE TITLE
File attachments open as downloads, rather than displayed.  

### ISSUE THREAD

**Issue by JigmeDatse** [ledgersmb/LedgerSMB#2680]
After attaching a file to a sales invoice, when I click on the link for the attachment, the file is downloaded, rather than displayed.  This may be quite a lot trickier to handle than I expect due to the fact that attaching something like a ODF when we attempt to display it could cause issues, and the current situation works "well enough" to not make things unworkable.  It just may be "unexpected behaviour" for some users.  

I see the GET parameters include "action=get".  I hope that we can find a way to get a design with how this will work.  This was mentioned (and asked how it worked) on Matrix:  [permalink](https://matrix.to/#/!qyoLumPqusaXqFJNyK:matrix.org/$1489459469519755DHnar:matrix.org).

**Comment by JigmeDatse** [comment]
I think that it likely opening in a new tab would be the desired way of handling this.

**Comment by hasorli** [comment]
Suggest to implement a document viewer, something like 
"ViewerJS - Documents. On your site. Now."  -  http://viewerjs.org/

**Comment by ehuelsmann** [comment]
Without the ViewerJS extension, the current behaviour was a conscious choice: I normally get annoyed by documents which I expect to download and then suddenly open in my browser (my browser offers an opportunity to open in a viewer locally, offering me a choice to view or download instead of being "forced" to view unless I remember to download explicitly)

**Comment by ehuelsmann** [comment]
Maybe therefore we want to discuss on the users mailing list?

**Comment by ehuelsmann** [comment]
ViewerJS doesn't do DOCX, XLSX, ...

I'm not sure we really need this. At this point things are working as designed.
