### ISSUE TITLE
No package for Stretch in Debian archive?

### ISSUE THREAD

**Issue by sampablokuper** [ledgersmb/LedgerSMB#2704]
https://ledgersmb.org/content/download says:

> A Debian package is available in Debian Jessie (stable), Jessie-backports, Wheezy (oldstable), Wheezy-backportsm, **and the current Debian Testing (Stretch)**.

However, https://packages.debian.org/search?keywords=ledgersmb&searchon=names&suite=all&section=all lists only:

> **Package ledgersmb**
    - wheezy (oldstable) (web): financial accounting and ERP program
    1.3.18-2: all
    - jessie (stable) (web): financial accounting and ERP program
    1.3.40-1: all
    - jessie-backports (web): financial accounting and ERP program
    1.4.33+ds-1~bpo8+1: all
    - sid (unstable) (web): financial accounting and ERP program
    1.4.34+ds-2: all

As no package for Stretch is listed, clearly this is at odds with the statement at https://ledgersmb.org/content/download .

What is the status of LedgerSMB for Stretch?

**Comment by ehuelsmann** [comment]
The package for Stretch was pulled in a very late phase because it had build problems. Unfortunately, those were not resolved timely, so that there has been no package in Stretch for two months now (I think).

Assigning @jame because he does the package maintenance at the moment. (Until others join the effort.)

**Comment by jame** [comment]
This is due not to an issue with LedgerSMB itself (although it does have an open bug on it related to LedgerSMB v1.4.x not being able to run from Apache because of the Perl version in Stretch), but because of one of the packages that the LedgerSMB package depends on, which is **dojo**.  That has a Release Critical FTBFS (Fails to Build from Source) Debian bug on it {[#852923](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852923)) which caused it to be removed  from Stretch which then caused any packages that depends on it, like ledgersmb, to be removed also.

**Comment by ehuelsmann** [comment]
Should we help the dojo maintainers so LedgerSMB can be added again?

Our at least put some pressure on the dojo team?

**Comment by jame** [comment]
What kind of help we can actually do I don't know but I'll at least be following the issue closer by subscribing to the bug and to the pkg maintainers mailing list.
And note that the dojo pkg is not the only RC (release critical) bug they'll be having to deal with.

**Comment by ehuelsmann** [comment]
Closing this item. We'll be posting Stretch packages on our own APT repo. Also, the description on the downloads page has now been updated to indicate there is indeed no Stretch package. (Stretch backports packages are planned at the time of writing.)
