### ISSUE TITLE
Error in Recurring Transactions processing vendor Invoices in 1.5.7

### ISSUE THREAD

**Issue by billott323** [ledgersmb/LedgerSMB#2973]
When "Processing Transactions" for recurring transactions involving vendor invoices, the follow error occurs:

```
Posting Vendor Invoice 420Status: 500 ISE Content-Type: text/html; charset=utf-8
Error!

'Not an ARRAY reference at /opt/ledgersmb/tools/../lib/LedgerSMB/IR.pm line 234. '

dbversion: 1.5.7, company: SalemStreetN
```
No transactions are posted. Logging back into the system is required to recover. Note:  "Processing Transactions" for recurring transactions involving AP transactions complete successfully.

**Comment by billott323** [comment]
I have verified that this error occurs on 1.5.8, as well

**Comment by ehuelsmann** [comment]
I'm afraid there's not much I can do at the moment about the "being logged out".

What's happening is: a new session is created (because a new `$form` is being created); however, due to the error, the transaction is being flushed (rolled back) and with it the new session. However, the cookie referring to the new session has already been provided to the browser, which tries to authenticate using this (now non-existing) session on the next request.

An option I'm discussing with @sbts is to try and create the session in its own (separate) transaction.
