### ISSUE TITLE
Changing a contact location type, clicking "Save Location" creates a _new_ location

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2984]
I.e., the "Save Location" button and "Save New Location" button seem to do the same thing - create a __new__ location. As such, any time you *edit* a location, you end up creating a new one.

Tested in v 1.4.41

**Comment by sbts** [comment]
@funkypenguin I believe this was fixed in early 1.5.x
Is it possible for you to upgrade?
1.4 has been oldstable since about September 2016 when we released 1.5

If there are reasons you can't easily upgrade, or you would like to discuss further,
Please Join our chat room at [#ledgersmb:matrix.org](https:riot.im/app/#/room/#ledgersmb:matrix.org)
There is someone around almost 24/7

**Comment by funkypenguin** [comment]
Thanks for the update - we will be rolling on to 1.5 in the next few months, after we nail some new dependency issues.

**Comment by sbts** [comment]
@funkypenguin can you describe the dependency issues?
Is there something we can do to help there?
