### ISSUE TITLE
Provide a mechanism to filter voided invoices from search

### ISSUE THREAD

**Issue by funkypenguin** [ledgersmb/LedgerSMB#2988]
When searching invoices, it's impossible to _not_ see all the VOIDed invoices. This is a usability problem, especially if you've voided a whole bunch of invoices while doing testing! Can a default-checked checkbox be added to the search interface to suppress voided invoices?

**Comment by sbts** [comment]
handling of Voided invoices has been significantly improved in 1.5.x
Fixing this in 1.4 was too invasive, so it was done in 1.5

As 1.4 is old stable, and we have a policy of only providing bugfixes, not feature changes nor functionality changes to old stable It's recommended to upgrade to resolve issues like this

Closing as won't fix

**Comment by ehuelsmann** [comment]
@funkypenguin, you may be running into the problem here that VOIDed invoices and their VOID-ing counterparties first need to be "paid" in order to disappear from the list of (open) invoices.

The payment is nothing more than a "zero-amount transaction" which posts the negative voiding amount against the positive voided amount. these invoices will then disappear from the list of open invoices.

**Comment by funkypenguin** [comment]
Noted, mentioning @Rachaelaprice FYI
