### ISSUE TITLE
Password Duration can be set to an invalid value preventing password change with a nonsensical error message

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3231]
If the `defaults -> Password Duration` setting is set to an invalid value, eg: 99999999999
You can't change your password.
Even Worse, the error message is
`Company does not exist`

Looking at the PG logs
```
2017-10-08 12:25:45.471 BST [8224] hillr@HHL ERROR: interval field value out of range: "99999999999 days"
￼2017-10-08 12:25:45.471 BST [8224] hillr@HHL CONTEXT:  PL/pgSQL function user__change_password(text) line 11 at assignment
```

So we need to validity check that Default Entry field, and also fix the error message.

Cricalixwood reported this after he set "Password Duration" to attempt to prevent 24 hour password expiry.

Obviously we need to do something about improving the notification that a password reset has been done, and a user "password change" is needed

**Comment by nick-prater** [comment]
In 1.5 and above, the misleading message has been replaced by a message to indicate that the password change was unsuccessful. A confirmation message is displayed on success.

1.6 and above enforce a database constraint to prevent invalid password durations, fixing the root cause of this issue.

1.7 and above have browser validation of the password duration before submission of the defaults form.
