### ISSUE TITLE
Cash Receipts Search doesn't honor amount minimum limits

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3270]
With no customer entered
Setting a minimum "total amount" of `>=1` doesn't prevent customers with zero amounts outstanding from being offered for selection.

Also, setting to a larger figure, and entering a partial customer name with multiple matches (hence needing to select from the radio list page) ignores the condition.

if one and only one customer matches the filter is honored

**Comment by ehuelsmann** [comment]
@sbts I think this is correct behaviour: the limit is applied to the amounts outstanding, not  to the customers.
Our payment screen *never* filters customers "without amounts to pay" because it's being (ab)used to enter overpayments.

**Comment by ehuelsmann** [comment]
I'm not sure this is a bug after-all/at all?

**Comment by ehuelsmann** [comment]
Rather, I think this *isn't* a bug. We could file an enhancement request as part of the payments UI restructuring.

**Comment by ehuelsmann** [comment]
When opening an enhancement request, I think that should be accompanied by a design/clear proposal. So, we better move this to the wiki in the mean time.

**Comment by sbts** [comment]
@ehuelsmann I can't agree with closing this as "not a bug" as the behaviour is inconsistent depending on the filters matching none, one or many entities.
Keep in mind, this is an issue with the "cash receipts search" feature, not the payments or receipts entry screens

**Comment by ehuelsmann** [comment]
@sbts, there's no "cash receipts search" functionality; I know we have "cash receipts" and "cash reports receipts". the latter doesn't have a limit selector, so I'm assuming you're referring to the former. The former however, explicitly includes all entities without outstanding amounts in order to support overpayments. Which is where I'm concluding that this may not be the behaviour you expected, but it works as designed.

**Comment by ehuelsmann** [comment]
Well, there *is* `Cash > Reports > Receipts`, but that doesn't have an amount criterion...
