### ISSUE TITLE
Doc base user

### ISSUE THREAD

**Issue by 0rir** [ledgersmb/LedgerSMB#3305]
What info can be acquired by-- and what damage can be done by a base user? 
How can a prospective user assess LSMB security absent some hints on this?

**Comment by ehuelsmann** [comment]
How can a prospective user assess security even *with* this documentation? I mean, there are lots of roles a user can be assigned. In order to assert security, one would need to have both documentation of the intent of the role as well as test that the role indeed is restricted to the documented purpose.

**Comment by ziuq** [comment]
Your point is germane, but a little off my target.  I was using my  "user's" voice and not so well.

Most of the users I have seen comment, clearly seem ready to trust the security Lsmb has implementated. I mean that any testing of role privileges is usually not contemplated.   That there is little documentation on all the roles is bad, but for most there is a correlation between the menu items and the role.   Seeing that a user/admin can make some seemingly reasonable decisions about them.

So what can a base user do?  What are their privileges?  Should there be un-promoted base users or not?

Reading your statement, I get the essence:  LedgerSMB cannot be secure because documentation is lacking.
I cannot find a good argument against that.
