### ISSUE TITLE
Unfinished transaction types: migration adds transaction types, but regular code doesn't

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#3363]
This change adds something known as a "transaction type":

   https://github.com/ledgersmb/LedgerSMB/blob/master/sql/changes/1.6/gl-trans-type.sql

While the migration sets up the transaction type content correctly, real code creating transactions, doesn't. (Or at least, it should be verified that it does.)

**Comment by ziuq** [comment]
Why is it blocking (allow nulls)?  Is information being lost in 1.6 vs. 1.5?

**Comment by ehuelsmann** [comment]
It's blocking because upon introduction of the new `trans_type` field the content of the fileld is set up with initial content for all GL transactions. After the initial creation/migration of data, the system is supposed to maintain the field itself, but currently does not.
Since the field is automatically set to `gl` when not supplied, I would argue that the information isn't completely lost, but we have no good tools in place to repeat the migration once we do complete this issue. So, better complete it before 1.6, was my thinking.

**Comment by ziuq** [comment]
Well, I commented because it weird to have a migration feature precede the the target's implementation of the feature.

It seems that the artifacts of each kind of transaction could be analysed afterward to fill this field.  If so, it seems not blocking.

Dumping 'indeterminate' and 'manually entered' together would be losing information;  but I was wrong to think that was an issue here.  Here 'gl' is not a SQL default:  a value to use if none is supplied.
It is a default in a procedural sense:  the last alternative.  This just caught me.

'gl' is a misleading abbreviation for 'manual'. 

Varchar(1000) seems a little long, maybe that could be cut down by a char or two.

Char(2) seems short if this is ever for presentation.  Large for the domain.

In the user domain, 'as' is a subset of 'ia'.  Which may or may not matter; there doesn't seem to be a business need driving this.

I don't see this as user data; so I don't believe it should be in a table in public.

**Comment by ehuelsmann** [comment]
Agreed that this isn't directly user data. It is however direct input to generate reports of user interest, such as the inventory activity report: https://github.com/ledgersmb/LedgerSMB/blob/master/sql/modules/Goods.sql#L199

**Comment by ziuq** [comment]
I misinterpreted an earlier comment;  I agree it blocks.

My thought was to post process as necessary:  diagnose null values  and change them at line 202 and if necessary in the closing process.  But I suppose tracking the points of input is not much more work.
