### ISSUE TITLE
Line breaks in Item descriptions don't display correctly 

### ISSUE THREAD

**Issue by sbts** [ledgersmb/LedgerSMB#3457]
This was reported by Angelene on the users mailing list.
if a multi-line description is entered (using shift-enter) in the description field on an order it's correctly displayed on screen, but fails when generating output for printing or emailing.

When generating the document as
- HTML output, linebreaks are just shown as <br> in the text
- PDF output, linebreaks cause a linefeed as expected but that breaks the tabulation
- CSV output, silently (to the user) fails to do anything

The issue with CSV output isn't within scope of this issue, but is noted here for completeness 

Currently, multi-line descriptions do work for Sales Invoices, but only when generating the output as PDF.
HTML output has the same issue as for Sales Orders

@ylavoie is checking if a workaround can be implemented in the output templates while we fix the underlying code and get that into a release.

Before closing this issue we need to test all output types that can contain multi-line data

**Comment by sbts** [comment]
Some Screenshots to show the issue.

---
![image](https://user-images.githubusercontent.com/11002795/36573810-ad4caf90-187d-11e8-87ca-07097716f217.png)
**1. The Sales Document source data (same for invoice or order)**

---
---

![image](https://user-images.githubusercontent.com/11002795/36573884-e7aac2b2-187d-11e8-97dc-276851ebe10f.png)
**2. The generated HTML Output Document**

---
---

![image](https://user-images.githubusercontent.com/11002795/36573925-14d2b8c6-187e-11e8-8604-14b01552029d.png)
**3. The generated PDF Output Document**

**Comment by ehuelsmann** [comment]
Found the root cause of this issue: There's code in Form.pm to transform `\n` -> `<br />` ('Form::format_string()`). This code is called in both `io.pl` and `arapprn.pl`. This is an ordering problem, because the "<br/> value" then gets passed to `Template::HTML::preprocess()` which finds the `<` and `>` characters and transforms those into `&lt;` and `&gt;`.

Estimated solution: phase out the use of `format_string()` (and compensate in each of the templates?)
