### ISSUE TITLE
create databases against 'stable' template0

### ISSUE THREAD

**Issue by ziuq** [ledgersmb/LedgerSMB#3495]
A low probability issue but catching this on a database restore could be difficult.

Postgresql database creation and restoration should be against the template0 database.  This would bring Lsmb practice in line with Postgresql's recommended practice since template1 is for site localizations which might conflict.

**Comment by ehuelsmann** [comment]
Did you run into an actual issue, or is this mainly a point of precaution? I haven't run into problems the way we do things now. Having a specific case where this hours wrong would be interesting to know of.

**Comment by ehuelsmann** [comment]
My reading of https://www.postgresql.org/docs/9.5/static/manage-ag-templatedbs.html is that restores should be done against copies of template0, but database creation is supposed to use template1.

**Comment by ziuq** [comment]
The installation of Lsmb is essentially a database restore.

I  disagree with your reading:  it does not say databases  _should_ be  created against template1 but that it is the _default_. 

This is just precautionary; security demands a known database state.   We cannot ensure that, but we can play nice.   Template0 is advisorily locked and template1 is not.

**Comment by einhverfr** [comment]
I agree we should create against template1. There are reasons people might want to add things to template1 that go into the dbs.  Monitoring extensions and other things.  By default, people don't install stuff in template1 but there are legitimate use cases for it.

**Comment by einhverfr** [comment]
@ziuq then in your view, we should never be able to have pg_stat_statements installed on a new lsmb db, right?

**Comment by ziuq** [comment]
Hi @einhverfr, not at all;  template1 is not necessary for that.

In my view are users who don't know what template0 and template1 are.  I assume their Pg install is good because
1)  it was installed per lsmb instructions,
2)  it was installed by apt or such and inertia left it okay,
3)  it is in a well admin'ed shop.
How good are these assumptions when a family member who is a CS student is drafted as primary tech?
What happens when the shop that wants stats, sees none?  Do they out number the drafted student
installs?
I am assuming there is an installation note that mentions template0 and lets the user know they are okay if 1 or 2 apply.

**Comment by einhverfr** [comment]
But that means you have to go in to the lsmb database directly after it is created and create the extension there, right?

It is a *very bad idea* to ever change template0, because that's the backup/restore diff db.  So if you ever change something there, you cannot safely restore your backup somewhere else.  So template1 gives you an ability to template initial db creation without messing up the portability of backups.

So the use case I am looking at is:  set the appropriate reloads for pg_stat_statements in the config files or using alter system, create the extension in template1, then create your lsmb dbs.  There is *no equivalent way* to do this if we create dbs off template0 without really messing things up.

**Comment by einhverfr** [comment]
Also principle of least surprise means sticking with defaults here.

**Comment by einhverfr** [comment]
Just to verify my understanding of intents of template0 and template1:

Template0 is the globally identical baseline database for creating and restoring portable logical backups between instances.

Template1 is the locally modifiable database creation template.

**Comment by ziuq** [comment]
No, as I recall, the extension is installed to the site.  The  modified template1 would just bring in a table or view to collect or facilitate collection.

I agree about keeping template0 pristine and template1 being for site wide instrumentation.

Least surprise was my point, but my concern was for the site that is not near knowing about pg_stats or templates.   I don't find your scenario compelling because I see it as more self healing, where stats are expected the expertise to get them is likely to exist.

I could be wrong in imagining that missing some stats on a new database is not dire.

**Comment by einhverfr** [comment]
> No, as I recall, the extension is installed to the site. 

Not quite right.

When you create a database you copy a template to a new OID-based directory.  So you install site-wide extensions to template1 and then copy from there.  That's the supported work-flow.  This means all extensions are copied over.

> I agree about keeping template0 pristine and template1 being for site wide instrumentation.

So then why would you say that extensions etc that someone wants site-wide and hence installs in template1 must NOT be available in LedgerSMB?

> Least surprise was my point, but my concern was for the site that is not near knowing about pg_stats or templates. I don't find your scenario compelling because I see it as more self healing, where stats are expected the expertise to get them is likely to exist.

What would a DBA expect?  I would think a DBA would expect anything in template1 to be present in all dbs created because that's the *designed* behavior of PostgreSQL.   Yes, it is possible to screw it up.  It's also possible to screw up things by modifying template0 but that is a little harder.  But all cases are recoverable.

My vote is to stick with designed behavior unless there is a truly compelling reason why designed behavior in PostgreSQL really doesn't work for us.  And I don't see "the user might mess it up" as making that case.

**Comment by einhverfr** [comment]
As a note, in my two decades of PostgreSQL experience I have *never* seen anyone decide to create production dbs from template0 outside of restoring from backup.  I *have* seen template1 be messed up but now it is pretty hard to accidently do that with our current setup scripts so if a user starts mucking around with the database, I would assume the user knows what they are doing.

I don't want to say "to protect advanced newbies from themselves we will disadvantage seasoned users."

**Comment by ziuq** [comment]
Okay,  I'll close this or you can beat me to it.

"to protect advanced newbies from themselves we will disadvantage seasoned users."
"mucking around with the database"
Those are the only real points where we have differed.

On the first, it is a judgment of who the users are.   I keep trying to get a good sense of the S vs. M population or target  of L**SM**B.  The more expert seem to be a small group but are apt to be more significant.   I keep getting info that makes the user base seem more and more small office, but I realize that the larger business can be more invisible. 

The second may just be semantic:  that someone doesn't have to mess with lsmb's database but just with the postgres install may be what you meant.

**Comment by sbts** [comment]
@ziuq
For the record I agree with @einhvefr and @ehuelsmann. 
Our current behaviour is inline with PG best practice and makes rational sense.

- Create new db's against template1 which is going to contain any site wide extensions that are installed
- backup and restore against template0 which is theoretically guaranteed to be pristine so all extensions in the db will be correctly backed up and restored as well.

If you look at this issue from an expectations perspective....
Any other behavior will cause 
- the knowledgeable to wonder what on earth we are thinking 
- the amatuer with knowledge will be relying on the many howtos and such out there which should all fall in line with best practice and work along the same lines as we do
- the novice will not touch the db directly without our documentation telling them to
- the various PG support paths (eg: IRC #postgres) will expect a best practice methodology and support will be complicated if we diverge from that


Overall I believe we have it correct and feel this issue can be closed as "based on invalid interpretation of ducumentation"
