### ISSUE TITLE
Printing invoice -- letterhead.tex not found in Template.pm line 612

### ISSUE THREAD

**Issue by mplubratt** [ledgersmb/LedgerSMB#3729]
I am using the 1.6.2 Docker image of LedgerSMB.  When I try to render an invoice PDF, I receive the following error:

Req:9A205DF47FAC11E8A6F2A7B034004217 2018/07/04 17:06:34 - ERROR - lsmb_legacy::catch {...}  /srv/ledgersmb/bin/../old/bin/old-handler.pl (174) -- 'Template error: file error - letterhead.tex: not found at /srv/ledgersmb/bin/../lib/LedgerSMB/Template.pm line 612.\n'

I have English(US) set as the default language.  I also made sure there were English(US) templates for both letterhead.tex and invoice.tex.

**Comment by ehuelsmann** [comment]
hi,

Thanks for taking the time to report your issue. Could it be that your database was upgraded from a version prior to 1.5? The issue would then probably be caused by 1.5 and newer dealing with template INCLUDEs a bit differently than 1.4 and older. The difference is detailed in the "Printed document templates" of https://ledgersmb.org/content/upgrading-ledgersmb-15

If this is your issue, you can go to the Invoice template through the menu: `System > LaTeX templates > Invoicing > Invoice`, click the "Edit" button at the bottom, search for the text `<?lsmb INCLUDE letterhead.tex ?>`  and replace that with `<?lsmb INCLUDE letterhead ?>` (Note the removal of the `.tex` extension.) And click the "Save" button at the bottom.

Hope that helps and please let us know if this helped!

Regards,


Erik.

**Comment by mplubratt** [comment]
Thank you, Erik.  I missed that part when I upgraded to 1.5.  Everything is now working!
