### ISSUE TITLE
ledgerSMB-manual.pdf p. 12 mentions non-existent tools/prepare-company-database.sh

### ISSUE THREAD

**Issue by cppljevans** [ledgersmb/LedgerSMB#3848]
I'm using the ledgersmb installed on ubuntu 18.04 by synaptic which says it's version 1.4.42+ds-1.
I also downloaded https://github.com/ledgersmb/LedgerSMB/raw/master/doc/LedgerSMB-manual.pdf.
Page 12 of that .pdf file says:

   An alternative method is the ’prepare-company-database.sh’ script contributed by Erik Huels-
mann. This script can be useful in creating and populating databases from the command line and it
offers a reference implementation written in BASH for how this process is done.

However, there's no such file.  There is a ’prepare-company-database.pl’ file; however, when that's
invoked it causes the following output:

evansl@larry-OptiPlex-9020:/usr/share/ledgersmb/tools$ perl -I.. prepare-company-database.pl --help
Failed to open ledgersmb.conf: No such file or directory at ../LedgerSMB/Sysconfig.pm line 103.
Died at ../LedgerSMB/Sysconfig.pm line 103.
Compilation failed in require at ../LedgerSMB/Auth.pm line 50.
BEGIN failed--compilation aborted at ../LedgerSMB/Auth.pm line 50.
Compilation failed in require at ../LedgerSMB/Database.pm line 34.
BEGIN failed--compilation aborted at ../LedgerSMB/Database.pm line 34.
Compilation failed in require at prepare-company-database.pl line 33.
BEGIN failed--compilation aborted at prepare-company-database.pl line 33.

The missing .sh file is also mentioned in the /usr/share/doc/ledgersmb/README.Debian.gz file.
Mentions of the .sh should be removed since there is no such file in the ubuntu package.

Is there some other way to call the prepare-company-database.pl script to avoid these errors?

**Comment by ehuelsmann** [comment]
Hi!

Actually, tools/prepare-company-database.sh *does* exist (in 1.4.42): In https://github.com/ledgersmb/LedgerSMB/tree/1.4.42 see https://github.com/ledgersmb/LedgerSMB/tree/1.4.42/tools/ with in it the script you mention.

The docs probably say that you have to remove the '.sh' extension because it's Debian policy not to add extensions identifying the used technology on scripts they distribute. On your system you should hence be searching for `prepare-company-database` instead of `prepare-company-database.sh`.

The errors produced by `prepare-company-database.pl` can be avoided by creating the non-existing file `ledgersmb.conf` which LedgerSMB::Sysconfig expects to exist.

In general, I'd like to advise you *not* to set up a 1.4 instance though: It's past its end of life for over a year now. You're way better off with either 1.5 or 1.6, both of which have community support for some time; 1.5 for little over a year, 1.6 a little less than 3 years.

Regards,

**Comment by ehuelsmann** [comment]
One reason to recommend 1.6 is that it can run without requiring `ledgersmb.conf` to exist.
