### ISSUE TITLE
Sales tax not included in amount due from Vendor invoice

### ISSUE THREAD

**Issue by smbgoodname** [ledgersmb/LedgerSMB#3941]
Version 1.6.8 Go to AP->Vendor Invoice. Create a invoice with items. Save and post the new invoice. The sales taxes are automatically calculated correctly. Go to Cash->Payment. Select the vendor. The amount due for the newly created invoice does not include the sales taxes.

All tax numbers have been entered for the vendor. Creating an AP->Add Transaction and posting it does include the sales taxes on the Cash->Payment amount due screen.

**Comment by ehuelsmann** [comment]
Thanks for reporting. It was quite tricky to find out what's going on in this case. I've identified the root cause being a missing hidden INPUT tag in the invoice HTML of the vendor invoice (which *is* part of the customer/sales invoice).

This regression is in all 1.5 versions and 1.6 versions so far.
