### ISSUE TITLE
AP-->Reports--> Vendor History not showing results

### ISSUE THREAD

**Issue by Bobberty** [ledgersmb/LedgerSMB#4361]
After entering several Purchase Orders and Vendor Invoices, I checked the Vendor History.
Using different search filters, there are no results.

**Comment by ehuelsmann** [comment]
There's an important thing about the history search: you get *either* invoices *or* orders, depending on the radio button on the third line above the "Include in report" label.

I *am* getting outcomes, so, maybe your selections were incompatible with the data in your database?

In order to get this issue resolved, could you create a clean company and describe the exact steps you're performing which then result in this unexpected behaviour (so I can replay these events and see where the problem comes from)?

**Comment by Bobberty** [comment]
I will do this within 24 hours.
Thanks.

**Comment by aungzwin10** [comment]
I found the similar issue which is not resolved yet but close. So I reopen this.

I have customer - "Default", credit account - "1234"

1. Create AR  > Sales Invoice for "Default" as shown in below screenshot and POSTED.
<img width="800" alt="Screen Shot 2021-06-14 at 10 25 38 AM" src="https://user-images.githubusercontent.com/31498748/121837119-e0c79a80-ccfa-11eb-9f46-d4b0e27d2749.png">

2. Create AR > Add Transaction for "Default" as shown in below screenshot and POSTED.
<img width="800" alt="Screen Shot 2021-06-14 at 10 31 01 AM" src="https://user-images.githubusercontent.com/31498748/121837449-a14d7e00-ccfb-11eb-80d6-01edae12f05f.png">

3. Create report, AR > Reports > Customer History. As the issue creator said, I tried multiple combination of filter(including without any filter value) but the empty list is returned.

**Comment by aungzwin10** [comment]
#5194 
  I have requested the documentation for Customer/Vendor History on the above issue.

**Comment by ehuelsmann** [comment]
@aungzwin10 on 1.9, I:

1. created a customer
2. created a service
3. entered and posted an invoice for 1 item of the service
4. ran the customer history report without selections

I get a single-line output for the customer as expected.

Are you using 1.9(or master) or 1.8?

**Comment by aungzwin10** [comment]
I have one question. Do all of your Vendor/Customer have location data?

I think I found the cause.
It is because of the country, in my vendor/customer entity, I don't record any 'Location'. And the query select according to the country in the purchase history.

The Country dropdown is set to current user country by default and it can't select blank one.

I have tested two ways,
1. setting 'country_id' to blank in the request parameter.
2. adding Location data to the customer/vendor
Both work.

Could you please add blank options to the country dropdown? So that user can select without country.

**Comment by ehuelsmann** [comment]
> Could you please add blank options to the country dropdown? So that user can select without country.

In 1.9 this has been taken care of and works out of the box. We need to explicitly enable this on 1.8.

**Comment by ehuelsmann** [comment]
Hmm. You probably set a default country in "System > Defaults". Then the country drop-down is auto-populated. (And in 1.8, there's no way to select an empty value.)
In 1.9, there's a possiblity to select an empty value. My test system did not have a default country selected, which circumvented this problem -- which explains why my test system gave me results even without providing locations to my customers.
