### ISSUE TITLE
Unable to get docker installation of LedgerSMB running

### ISSUE THREAD

**Issue by gwhitney** [ledgersmb/LedgerSMB#4720]
As requested in #4655, I tried once again to go from a fresh Debian 9 instance to a running LedgerSMB using docker-compose, and have been unable to get something usable runnable. I don't mean to use your issue system as a tutorial request, but I have tried faithfully to follow all of the documentation I was able to find, so I thought that filing an issue might not be unwelcome if it would allow some clarification or elaboration of the documentation that might ease the path for others interested in trying out LedgerSMB.

Here are the exact steps I followed:
1) Spun up a fresh Debian 9 ("stretch") instance (on Linode), with a non-root sudo-enabled user "ledgersmb". Logged in as ledgersmb.
2) Followed the instructions at https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-9 to install docker-compose
3) git clone https://github.com/ledgersmb/ledgersmb-docker.git
4) cd ledgersmb-docker
5) docker-compose pull
6) docker-compose up -- This produced a bunch of messages all of which looked reasonable
OK, so now I presume I have a running LedgerSMB at localhost:5762. I understand I need to connect https://mydomain.tld to this. I have the most experience with Apache (although I am not an expert with any web server), so I will try to install Apache and use it as a proxy for LedgerSMB.
7) Log in again to my server (as the login where docker-compose executed is now unresponsive)
8) sudo apt-get install apache2 certbot python-certbot-apache
9) sudo certbot certonly  --apache -d mydomain.tld -d www.mydomain.tld
10) I know I need a site .conf file for apache, so I figure the easiest is to grab the one from the LedgerSMB code repository and edit it: sudo curl https://raw.githubusercontent.com/ledgersmb/LedgerSMB/master/doc/conf/apache-vhost.conf -o /etc/apache2/sites-available/ledgersmb.conf
11) sudo nano /etc/apache2/sites-available/ledgersmb.conf -- replaced YOUR_SERVER_NAME with my server name (what I've been calling mydomain.tld, but of course that's not really the domain name), replaced SSL_CERT_FILE, SSL_KEY_FILE, and SSL_CHAIN_FILE with the corresponding files in /etc/letsencrypt/live, and finally, not knowing what WORKING_DIR should be for this Docker setup, I just deleted WORKING_DIR, leaving the DocumentRoot as /UI.
12) sudo a2ensite ledgersmb
13) sudo a2enmod ssl rewrite proxy proxy_http
14) sudo systemctl restart apache2

I figured at this point everything should be in place and ready to go. So in a browser, I visit "https://mydomain.tld/" and unfortunately all I get in my browser is the message: "503 Service Unavailable -- The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.25 (Debian) Server at [mydomain.tld] Port 443"

The last two lines of /var/log/apache2/error.log are:
[Sat Jun 13 02:51:43.978682 2020] [proxy:error] [pid 14002:tid 140627262027520] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:5762 (*) failed
[Sat Jun 13 02:51:43.978803 2020] [proxy_http:error] [pid 14002:tid 140627262027520] [client 76.175.65.95:58132] AH01114: HTTP: failed to make connection to backend: localhost

Any tips, helps, pointers on what I've done wrong or how to make it possible to connect to this installation of LedgerSMB are very much welcome.

(Note that by a similar process but operating from distribution tarballs, I _have_ managed to get a working LedgerSMB installation. I am posting the issues with getting it working via Docker at the request of those who responded to #4655 about my difficulties with doing the same for an installation directly from github.)

**Comment by ehuelsmann** [comment]
Thanks for taking the time to file your report!

> As requested in #4655, I tried once again to go from a fresh Debian 9 instance to a running LedgerSMB using docker-compose, and have been unable to get something usable runnable. I don't mean to use your issue system as a tutorial request, but I have tried faithfully to follow all of the documentation I was able to find, so I thought that filing an issue might not be unwelcome if it would allow some clarification or elaboration of the documentation that might ease the path for others interested in trying out LedgerSMB.
> 

Absolutely! And we expect to use your input to both create a simpler as well as better documented process. Hopefully you can enjoy that too.

> Here are the exact steps I followed:
> 
>     1. Spun up a fresh Debian 9 ("stretch") instance (on Linode), with a non-root sudo-enabled user "ledgersmb". Logged in as ledgersmb.
> 
>     2. Followed the instructions at https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-9 to install docker-compose

So far so good. Adding these steps to your reproduction recipe helps to understand what your base line.

>     3. git clone https://github.com/ledgersmb/ledgersmb-docker.git

I understand you using this command. However, it results in a container which runs our latest development branch instead of the latest release. the correct command would have been:

```bash
git clone -b 1.7  https://github.com/ledgersmb/ledgersmb-docker.git
```

However, as part of the simplification, we've changed the default branch, so re-running your original command will get you the same.

>     4. cd ledgersmb-docker
> 
>     5. docker-compose pull

*If* you re-run the clone command above and you run this command again, that gets you in a much better position: it'll pull LedgerSMB 1.7.15 (our latest release) for you.
 
>     6. docker-compose up -- This produced a bunch of messages all of which looked reasonable
>        OK, so now I presume I have a running LedgerSMB at localhost:5762. I understand I need to connect https://mydomain.tld to this. I have the most experience with Apache (although I am not an expert with any web server), so I will try to install Apache and use it as a proxy for LedgerSMB.

Running `docker-compose up` will run the container in the foreground. If you want to run the container in the background, please run `docker-compose up -d`.

Unfortunately, the version of `docker-compose.yml` file doesn't make LedgerSMB available on `localhost:5762`. However, I just committed a change which explicitly binds the container to `127.0.0.1:5762`. So, if you follow my advice above to do a new clone, you should also get a new `docker-compose.yml` which creates the correct port-binding.

>     7. Log in again to my server (as the login where docker-compose executed is now unresponsive)

I think you can probably kill the docker-compose command using Ctrl-C? At least, that's how it works for me... However, that also kills the container itself. Starting the container in "daemon mode" using the `-d` option resolves that.

>     8. sudo apt-get install apache2 certbot python-certbot-apache
> 
>     9. sudo certbot certonly  --apache -d mydomain.tld -d [www.mydomain.tld](http://www.mydomain.tld)

Ok. Good. These should work.
 
>     10. I know I need a site .conf file for apache, so I figure the easiest is to grab the one from the LedgerSMB code repository and edit it: sudo curl https://raw.githubusercontent.com/ledgersmb/LedgerSMB/master/doc/conf/apache-vhost.conf -o /etc/apache2/sites-available/ledgersmb.conf

That should work, although it lists "localhost:5762" which should probably be replaced by "127.0.0.1:5762" because the binding I listed doesn't include binding the IPv6 address (which localhost might include).

>     11. sudo nano /etc/apache2/sites-available/ledgersmb.conf -- replaced YOUR_SERVER_NAME with my server name (what I've been calling mydomain.tld, but of course that's not really the domain name), replaced SSL_CERT_FILE, SSL_KEY_FILE, and SSL_CHAIN_FILE with the corresponding files in /etc/letsencrypt/live, and finally, not knowing what WORKING_DIR should be for this Docker setup, I just deleted WORKING_DIR, leaving the DocumentRoot as /UI.

That will work. If you find LedgerSMB "sluggish", there's an option to make it faster by making the document root contain specific LedgerSMB content, though. I can explain in a follow-up.

>     12. sudo a2ensite ledgersmb
> 
>     13. sudo a2enmod ssl rewrite proxy proxy_http
> 
>     14. sudo systemctl restart apache2
> 

Those all look good.

> 
> I figured at this point everything should be in place and ready to go. So in a browser, I visit "https://mydomain.tld/" and unfortunately all I get in my browser is the message: "503 Service Unavailable -- The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
> Apache/2.4.25 (Debian) Server at [mydomain.tld] Port 443"
> 
> The last two lines of /var/log/apache2/error.log are:
> [Sat Jun 13 02:51:43.978682 2020] [proxy:error] [pid 14002:tid 140627262027520] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:5762 (*) failed
> [Sat Jun 13 02:51:43.978803 2020] [proxy_http:error] [pid 14002:tid 140627262027520] [client 76.175.65.95:58132] AH01114: HTTP: failed to make connection to backend: localhost

By default, docker-compose binds to an alternative IP address (not 127.0.0.1 but rather one in the 172.16.0.0/12 range). With the changes I just committed, you should find that the address "127.0.0.1:5762" now *does* get bound by the LedgerSMB service. (It may be required to restart Apache to detect that.)

> 
> Any tips, helps, pointers on what I've done wrong or how to make it possible to connect to this installation of LedgerSMB are very much welcome.
> 
> (Note that by a similar process but operating from distribution tarballs, I _have_ managed to get a working LedgerSMB installation. I am posting the issues with getting it working via Docker at the request of those who responded to #4655 about my difficulties with doing the same for an installation directly from github.)

Hope this helps and let us know if /when you have further issues!

**Comment by gwhitney** [comment]
I can verify that now this procedure as amended in your comment brings up LedgerSMB 1.7.15 for me. Thanks so much!

**Comment by ehuelsmann** [comment]
Thanks for verifying. I've created https://ledgersmb.org/content/installing-latest-ledgersmb-using-docker-compose to list the instructions. Additionally, I'm looking at updating the instructions in the Docker image to point to that page too.

**Comment by gwhitney** [comment]
The new docker-compose installation outline on the website looks great. That would have been exactly what I needed when I was first evaluating LedgerSMB. (As it was, I almost switched to Beancount/Fava, and only came back to give LedgerSMB a second look when it became clear that I'd basically be implementing Fund accounting from scratch on top of Beancount/Fava, as opposed to hopefully just adjusting the existing Funds so they categorize Asset/Liability accounts as well as Revenue/Expense accounts.) My only comment on the new web page is that maybe it's not 100% crystal clear that steps 8 and 9 are the implementation of what's described in step 7, so the readers don't have to separately figure out how to do step 7 on their own. So I might suggest taking the description in step 7 out of the numbering (making it an unnumbered comment), or conversely, renumbering 8 and 9 as 7.a. and 7.b. or something like that.

**Comment by ehuelsmann** [comment]
Thanks for the review and comments. I've taken your advice to make 8 and 9 sub-items of 7. Off to change the documentation to point at that specific page now.
