### ISSUE TITLE
1.8:Duplicate Sale/Employee option after update

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#5114]
In AR/AP > Add transaction, Sale/Employee dropdown options are duplicate when clicking update

![image](https://user-images.githubusercontent.com/31498748/93977349-57ed8500-fda0-11ea-872f-da73e3b2b51b.png)

**Comment by ehuelsmann** [comment]
@aungzwin10 , please test the above PR(s).

**Comment by aungzwin10** [comment]
@ehuelsmann , These PR fix the issue for update. But when we choose Customer/Vendor, it is still duplicate.

**Comment by ehuelsmann** [comment]
Ok. Which exact steps for you take to get that result and what is your"Mac per drop-down" setting?

**Comment by aungzwin10** [comment]
1. AR/AP > Add Transaction.
2. Select Customer/Vendor
Check the salesperson/employee dropdown, you will see the duplicate.

Max per drop-down is not set. Leave it empty.

**Comment by ehuelsmann** [comment]
Ok. The PR has been adjusted to fix both the duplication coming from is.pl (in the invoice) as well as the duplication coming from aa.pl (in the transaction).

Remaining issue is the salesperson getting "lost" on the first "Update" when the customer gets selected. You didn't see that yet, but basically, that update completely rebuilds the invoice from scratch, meaning that from the point of view of the code, this behaviour makes sense.

I'm  going to claim that the behaviour is consistent and "good enough". So that the current PRs are good enough to close this issue and we need to focus on getting replacement infrastructure in place instead of trying to fix the first "Update".
