### ISSUE TITLE
Date/time field value out of range on Journal Entry Update

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6040]
Below error encounter on `Update` of Journal Entry. User preference for date format is set to `dd-mm-yyyy`. It worked well with that date format in 1.8
```
'SELECT * FROM business_unit__list_by_class(?, ?, ?, 'false') ERROR: date/time field value out of range: "27-09-2021" LINE 1: SELECT * FROM business_unit__list_by_class('8', '27-09-2021'... ^ HINT: Perhaps you need a different "datestyle" setting. at ../old/bin/gl.pl line 546. '

dbversion: 1.9.1-dev, company: testdb
```

**Comment by ehuelsmann** [comment]
The date style is set here: https://github.com/ledgersmb/LedgerSMB/blob/master/old/lib/LedgerSMB/Form.pm#L1229-L1230

In 1.9 the code changed versus 1.8 as part of the  change to move to column-based user settings instead of row-based. In 1.9 the query is:

```sql
select "value" from user_preference join users using(id)
                      where "name" = 'dateformat' and username = CURRENT_USER
```

whereas in 1.8 the query used to be:

```sql
select dateformat from user_preference join users using(id)
                      where username = CURRENT_USER
```

@aungzwin10 can you indicate if these two return the same outcome on your 1.8 and 1.9 versions?

**Comment by ehuelsmann** [comment]
In a new company, this works for me. Could you create a screen recording to show me the problem?
