### ISSUE TITLE
Loading a Hierarchical COA does not appear to correctly set the heading for top level accounts

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6068]
This bug was identified by @aungzwin10 and more info appears in PR #6057
> Parent of CURRENT ASSETS is ALL ASSETS, right? But it is not set. @neilt Please check your CURRENT ASSETS whether or not heading dropdown is correctly selected to ALL ASSETS.

After loading the US GeneralHierarchical.xml file the detail asset headers `CURRENT ASSETS`, `INVENTORY ASSETS`, and `CAPITAL ASSETS` are NOT set with the parent as `ALL ASSETS`.

Also the same problem exists for `ALL LIABILITIES`. Neither of the sub-accounts `CURRENT LIABILITIES` or `LONG TERM LIABILITIES` are loaded with the heading set to  `ALL LIABILITIES`.

The same applies for the sub accounts of `NET MARGIN`.

**Comment by aungzwin10** [comment]
@ehuelsmann
This is different issue with setting current earning. I think you misunderstood.
This issue is about the Account Heading not set it parent heading.

https://github.com/ledgersmb/LedgerSMB/blob/3b570e0430d7652077f64db507339aef68fd1c9a/locale/coa/us/GeneralHierarchical.xml#L4-L23
In the above xml, Parent heading of `CURRENT ASSETS`, `INVENTORY ASSETS`, etc. should select `ALL ASSETS`. But it doesn't set the parent for heading. See the screenshot below.
<img width="530" alt="Screen Shot 2021-10-01 at 8 43 03 AM" src="https://user-images.githubusercontent.com/31498748/135555138-9ec5b6cd-133c-4e92-90b7-e5e1aed9c367.png">

It should select like below.
<img width="508" alt="Screen Shot 2021-10-01 at 8 43 36 AM" src="https://user-images.githubusercontent.com/31498748/135555148-1eaf926c-923c-4bf8-80b5-9bdd7767021c.png">


Value for parent_id column in account_heading table is empty.
```
 id | accno | parent_id |            description            | category 
----+-------+-----------+-----------------------------------+----------
  1 | 1000  |           | ALL ASSETS                        | 
  2 | 1050  |           | CURRENT ASSETS                    | 
  3 | 1500  |           | INVENTORY ASSETS                  | 
  4 | 1800  |           | CAPITAL ASSETS                    | 
  5 | 2000  |           | ALL LIABILITIES                   | 
  6 | 2050  |           | CURRENT LIABILITIES               | 
  7 | 2600  |           | LONG TERM LIABILITIES             | 
  8 | 3299  |           | TOTAL EQUITY                      | 
  9 | 3300  |           | SHARE CAPITAL                     | 
 10 | 3500  |           | RETAINED EARNINGS                 | 
 11 | 3999  |           | NET MARGIN                        | 
 12 | 4000  |           | GROSS MARGIN                      | 
 13 | 4005  |           | SALES REVENUE                     | 
 14 | 4400  |           | OTHER REVENUE                     | 
 15 | 5000  |           | COST OF GOODS SOLD                | 
 16 | 5400  |           | OPERATIONAL EXPENSE               | 
 17 | 5405  |           | PAYROLL EXPENSES                  | 
 18 | 5600  |           | GENERAL & ADMINISTRATIVE EXPENSES | 
(18 rows)
```

Normal Account are set it parent properly. See below
<img width="904" alt="Screen Shot 2021-10-01 at 8 48 23 AM" src="https://user-images.githubusercontent.com/31498748/135555506-7b6fd97e-6ee3-478e-8ed8-85b005d92883.png">
