### ISSUE TITLE
Num2text improvement needed

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6216]
old/lib/Ledgersmb/Num2text.pm (translates numbers into words).

- [ ]  Correctly translate for decimal number
- [ ]  Correct wording the number
- [ ]  Since Num2text is mostly used for money, should we consider the unit? 
e.g **`$ 567.89`** translates as **`Five Hundred Sixty-Seven Dollars and Eighty-Nine Cents`**

**Comment by ehuelsmann** [comment]
@aungzwin10 since the function is used for check printing, it actually does what it should (i.e. return `Five Hundred Sixty-Seven`?)

However, it would be much better to depend on modules in the Perl ecosystem which have this functionality built for us, for each language so we can build on that instead.

**Comment by aungzwin10** [comment]
@ehuelsmann Yes, it returns `Five Hundred Sixty-Seven`. Since we don't need to make changes on Num2text, I will close this issue.
