### ISSUE TITLE
Printing Checks with Cash -> Voucher -> Payments fails to include all invoices in the voucher portion of the check stub

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6253]
Attached video demonstrates the problem.

https://user-images.githubusercontent.com/1809796/145034508-2902ea72-8957-4f8a-8a03-8bb140e72466.mov

This is a repeat of the problem mentioned yesterday in chat.

1. Create a person contact with a single vendor credit account
1. Add Address to person vendor credit account.
1. Go to AP -> Add Transaction
1. Add two transactions with one line item each. Does not seem to matter which accounts you pick.
1. Go to Transaction Approval and approve both.
1. Go to Cash -> Vouchers -> Payments
1. Create a new batch.
1. In filtering payments select the vendor added in 2.
1. Start source numbering at 1000
1. Click Continue.
1. Select the Account added in 2.
1. Make sure All is selected and click print. Make sure Screen and PDF is selected. Although I do not have any other options.
1. The resulting check pdf is as shown above with only 1 of the 2 AP Transactions printed in the check voucher area. Expected to see both.

**Comment by aungzwin10** [comment]
@ehuelsmann @neilt 
I found why print only contain one invoice.
It is because of this code https://github.com/ledgersmb/LedgerSMB/blob/beb9b241b712193e0c50ca1d913d41783a1531f1/lib/LedgerSMB/Scripts/payment.pm#L475-L482

`check_max_invoices` is the system setting which you can set in System > Defaults > Max Invoices per Check Stub(under Misc Settings section). For most of the database(if user doesn't set manually) that setting will be null. So when the condition is check, it goes to `else` block and  set invoice count as 1 always.

I think we need to check null for `check_max_invoices` and if it is, include all invoices? How do you think?

**Comment by neilt** [comment]
Yes, no entry in `check_max_invoices` should default to showing all.  I fully expected that my voucher might overrun when testing.
