### ISSUE TITLE
Foreign exchange gain/loss line doesn't post if default is not set

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6360]
When foreign currency invoices are paid in Cash > Payment, there is a foreign exchange gain or loss occur. But if Foreign Exchange gain and loss account are not set in System > Defaults, payments are posted without gain/loss line. So debit and credit are not balanced for that invoices. See example below
<img width="1309" alt="Screen Shot 2022-01-13 at 3 19 38 PM" src="https://user-images.githubusercontent.com/31498748/149297196-c3ad3cc3-e323-4ce4-b476-317e9234a214.png">

I think this is an accounting bug. System should not post payment and show error if gain/loss accounts are not set. How do you think?

**Comment by ehuelsmann** [comment]
@aungzwin10 totally agreed that this is an accounting bug. Is this a bulk or a single payment? (From the screen, it looks like this is a GL Journal search; not a payment extract, so I'm not sure.)

**Comment by ehuelsmann** [comment]
@aungzwin10 I've found

https://github.com/ledgersmb/LedgerSMB/blob/337e5b26a72277894c51863beda84f0701b87282/sql/modules/Payment.sql#L991

which skips posting the gain/loss amount if there's no gain/loss account. I think the criterion should be changed to:

```sql
        IF fx_gain_loss_amount <> 0.00 THEN
```

This only fixes the problem *if* your problem is about a "single payment". That is, this code path doesn't get triggered through Cash > Vouchers > Receipts/Payments. Could you confirm this is indeed the situation you're running into?

Note: I'm trying to prevent the data from getting into the database (after all, it's an unbalanced transaction!), before looking at ways to improve user experience.

**Comment by ehuelsmann** [comment]
@aungzwin10 I've found a similar pattern in bulk posting:

https://github.com/ledgersmb/LedgerSMB/blob/337e5b26a72277894c51863beda84f0701b87282/sql/modules/Payment.sql#L740-L754

Seems we need to check and throw an error if there are empty values in the handling of the gain/loss account lookup a bit higher up:

https://github.com/ledgersmb/LedgerSMB/blob/337e5b26a72277894c51863beda84f0701b87282/sql/modules/Payment.sql#L613-L624
