### ISSUE TITLE
Server always return 500 on authentication fail

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6380]
Although the frontend expect some specific http status for error message, server always return 500.

https://github.com/ledgersmb/LedgerSMB/blob/98cda53b41064ca3dafd721015b1e16f6e86394e/UI/src/components/LoginPage.vue#L73-L85

**Comment by ehuelsmann** [comment]
The problem is this bit of code:

https://github.com/ledgersmb/LedgerSMB/blob/a442edb5c21bbd1c54afc8b1f309f089e67aebe9/lib/LedgerSMB/Middleware/Authenticate/Company.pm#L99-L103

which assumes that 'connect' returns `undef` when a connection problem happens. However, 

https://github.com/ledgersmb/PGObject-Util-DBAdmin/blob/09e9262cf54fa0e6e5dec2cc918ed026f6d4c542/lib/PGObject/Util/DBAdmin.pm#L523-L528

shows that in reality it throws an error.
