### ISSUE TITLE
Tax Form report can run

### ISSUE THREAD

**Issue by aungzwin10** [ledgersmb/LedgerSMB#6458]
Error occur on the `Tax Form > Report` run. The error message is attached below.

<img width="827" alt="Screen Shot 2022-03-17 at 10 44 39 AM" src="https://user-images.githubusercontent.com/31498748/159199976-6cece2b9-e93a-4f3a-bfaf-d21cb94ef76d.png">

Please feel free to let me know if you need more detailed information.

**Comment by ehuelsmann** [comment]
I'd love to solve this, but I'm pretty sure that simply running `Tax Form > Report` doesn't cut it: it runs fine on my database (1.9.11), with a tax form defined (but nothing allocated to the form). However, since this error is from the Details.pm code, I also think there's additional clicking or additional filters going on, because the Details code isn't touched in the selections (no selections) I'm using.

Could you please add an exact list of steps?
