### ISSUE TITLE
Entering a new service from Sales Invoice view gives error

### ISSUE THREAD

**Issue by neilt** [ledgersmb/LedgerSMB#6530]
### Version

1.9.13

### What browsers are you seeing the problem on?

Firefox

### What happened?

1. Go to Ar -> Sales Invoice
2. Select Any Customer
3. For the first item enter a new unique Description but no Number
4. Hit Update button.
5. System automatically navigates to `Item Not on File!'
6. Select Service
7. Hit Update button.
8. At the "Add Service" view enter a Sell Price
9. Hit Save button.
10. Get error.

````
'Can't use string ("ARRAY(0x560eba504d18)") as an ARRAY ref while "strict refs" in use at old/lib/LedgerSMB/Form.pm line 1092. '
````

### What should have happened?

Should have added the new service.

**Comment by ehuelsmann** [comment]
The only situation I'm able to reproduce this problem is when there are *no* other parts in the system. I guess we need to remove the code path which deals with setting up a part/service when there are no others in the system, because it creates the impression this is how to add parts, but it only works once...
