### ISSUE TITLE
Search invoices report not following user selected criteria

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#6670]
### Version

1.10-dev but applies to previous versions too.

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Use a company with multiple applicable taxes
- Use Search for AP/AR invoices
- Select `Tax Status` to `Taxable`
- Select a _specific_ `Tax Account`
- Submit

Data shown will display all applicable invoices with the total of all taxes for each invoice instead of the selected one only.

### What should have happened?

The tax displayed should reflect the user criteria.
There should be an indication that partial data is returned for each entry as other taxes won't be shown.

**Comment by ehuelsmann** [comment]
As discussed, i disagree with this assessment: the report is searching for invoices and allows selection of invoices based on whether they affect a specific tax account. The propose of the report is *not* to search for the tax amounts posted to a specific tax account by invoice. The latter is a valid request that we currently don't service well at the moment. I'm willing to write the code needed to do so, but that isn't what this issue is about. (Also, i can't commit short term to actually doing the work involved.)
