### ISSUE TITLE
Databases created before non-standard schema should be migrateable

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/LedgerSMB#6800]
### Version

1.10 but applies to previous versions too.

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

Databases crated before the introduction of non-standard schema are not recognized by setup when a schema is specified in configuration

### What should have happened?

Migration should be able to recognize databases, regardless of schema and migrate them using the schema ordered.

**Comment by ehuelsmann** [comment]
I do see your point. I'm wondering, though, what this means: the default schema has not changed, so almost no installations will be affected. Should detection run across all  available schemas? If so, what to do with old schemas that originated from old migrations? I.e. the `lsmb13` schema and friends?

**Comment by ehuelsmann** [comment]
@ylavoie, given that older databases contain lsmb12, lsmb13, sl28, sl30 or other pre-migration schemas, how should we decide which schema to migrate where to?

**Comment by ehuelsmann** [comment]
I've given this some more thought, but I think that although there *could* be __some__ users which want this, I think the large majority won't even know we support non-standard schemas. As for the default settings: nothing changed. Only our development settings in order to make sure this setup keeps working. But other than that, I don't see much to be done here.
