### ISSUE TITLE
Join bug in employee__all_managers()

### ISSUE THREAD

**Issue by joelonsql** [ledgersmb/LedgerSMB#7197]
### Version

1.11.0-dev

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

I stumbled upon a LEFT JOIN that must be incorrect, since none of the join conditions contain any columns from the joined table, that is, `person mp`.

```sql
CREATE OR REPLACE FUNCTION employee__all_managers()
RETURNS setof employee_result AS
$$
   SELECT p.entity_id, e.control_code, p.id, s.salutation, s.id,
          p.first_name, p.middle_name, p.last_name, ee.is_manager,
          ee.startdate, ee.enddate, ee.role, ee.ssn, ee.sales, ee.manager_id,
          mp.first_name, mp.last_name, ee.employeenumber, ee.dob, e.country_id
     FROM person p
     JOIN entity_employee ee on (ee.entity_id = p.entity_id)
     JOIN entity e ON (p.entity_id = e.id)
LEFT JOIN salutation s on (p.salutation_id = s.id)
LEFT JOIN person mp ON ee.manager_id = p.entity_id
    WHERE ee.is_manager
 ORDER BY ee.employeenumber;
$$ LANGUAGE SQL;
```

This line looks incorrect: `LEFT JOIN person mp ON ee.manager_id = p.entity_id`
One would expect e.g. `mp.entity_id` on one or the other side of the equality expression.

I think it should be: `LEFT JOIN person mp ON ee.manager_id = mp.entity_id`

Also, you should add this foreign key:
```sql
ALTER TABLE entity_employee ADD FOREIGN KEY (manager_id) REFERENCES person (entity_id);
```
As otherwise one could assign a non-person as the manager.

### What should have happened?

The function should return the correct result.

**Comment by ehuelsmann** [comment]
> Also, you should add this foreign key:
> 
> ```sql
> ALTER TABLE entity_employee ADD FOREIGN KEY (manager_id) REFERENCES person (entity_id);
> ```
> 
> As otherwise one could assign a non-person as the manager.

This is definitely a good point. After discussion on the chat channel we've come to the conclusion that it'd be correct to add this constraint, it's not known if there are any databases which have (ab-)used the current lack; on upgrade, we'd need to offer an upgrade to the data before installing the constraint (so that the existing data complies with the constraint). It's unclear what options we have for the upgrade code to modify the data. Do you have an idea as to what we can do here?
