### ISSUE TITLE
Incorrect primary key in table account_link?

### ISSUE THREAD

**Issue by joelonsql** [ledgersmb/LedgerSMB#7198]
This line made me curious: https://github.com/ledgersmb/LedgerSMB/blob/914754b541d66aa67e29be508262dc82b795e9d4/sql/modules/arap.sql#L72

Since account_link's PK is (account_id, description), that means one and the same `account_id` could occur multiple times in this table with different `description` values, which would cause duplication in the query mentioned.

I think the PK should just be on just (account_id), or is it something that I don't understand here?

**Comment by ehuelsmann** [comment]
Hi! Thank you for your thorough review!

The primary key of the table is correct and so is the query, from a functional perspective. However, maybe you can help with ideas to code that into the DDL.

The thing is: the account_link table contains a list of properties per account, one property per row. The account_link_description table records characteristics of account_links. If the description has a "summary" value of TRUE that link *must* be the only link on the account. Otherwise, there can be many.

What do you think is the best way to code that into the schema?

**Comment by ehuelsmann** [comment]
The suggestion I received from the PostgreSQL community is to use a "select for update" on the `account` table while updating (inserting/deleting/modifying) records in account_link, because that way, the trigger can check that there are no summary records inserted when there are already other records in the account link table (and vice versa).
