### ISSUE TITLE
shipto* variables do not use Shipping addresses

### ISSUE THREAD

**Issue by freelock** [ledgersmb/LedgerSMB#7453]
### Version

1.10.17

### What browsers are you seeing the problem on?

This problem isn't browser related

### What happened?

The invoice template populates a bunch of variables from the contact account. There is one set of variables for the address, email addresses, etc, and a different set prefixed with "shipto" presumably for the shipping addresses.

However, the shipto* versions all contain the same values as the non-shipto variables, even when there are different billing and shipping addresses set.

I tested moving the two addresses around between billing, sales, and shipping. Only the "Billing" address was used, for both the unprefixed and the shipto-prefixed variables. Sales and shipping addresses were entirely ignored.

### What should have happened?

The "shipto" variables should populate with the shipping details, if they are set, and only use the billing address info if they are not set.

There should be clear rules around how the template variables get populated, ideally shown on the template editing screens.

**Comment by ehuelsmann** [comment]
Not saying that this is the intuitive process, but you have to select Ship To from the invoice in order to activate a shipto address. However, currently that doesn't work (which is what the PR is about).

Agreed on the fact that (more) documentation is required with respect to the population of the invoice template variables. A good start there would be if the data that *should* be saved actually gets saved...
