### ISSUE TITLE
Make URLs bookmarkable

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/LedgerSMB#850]
Now that URLs are of the structure, due to the Dojo backbutton work:

<server>/login.pl#<hash identifying content of maindev>

It would be very nice if pages with a URL like that could be bookmarked and reloaded later.

**Comment by ehuelsmann** [comment]
The request means the following request flow:

* If there's no active session(cookie), establish a login session
* Once there's a session, load the  main page, with the menu on the left
* When the menu successfully loaded, load the content designated by the hash into the 'maindiv'

**Comment by einhverfr** [comment]
I think our autologout structure should handle the missing session cookies.  What is missing is what db one is connecting to.  I suspect this can be fixed by adding `&company=$db` to the end of the urls....

**Comment by einhverfr** [comment]
hmm not quite working and I guess js migh tnot have access to this and would have to pull from the cookie so not quite bit sized.....  but still shouldn't be too big.

**Comment by ehuelsmann** [comment]
If we're changing URL structure, I'd like the company name to be included in the URL path; this allows multiple cookies to be set against a single server -- thus allowing to be logged in on several instances.

**Comment by einhverfr** [comment]
Agreed, but that may not be fully possible until 1.6 or 1.7.  I think we can make links bookmarkable in 1.5 though.

It occurs to me that the real issue is that the company name needs to be a part of the query parameters for the main page, not the subpage.  I will try to get this done for 1.5.

Depending on how things go with the Dancer web-tool integration in 1.6, we can very likely fix the urls in 1.6
