### ISSUE TITLE
AP Add Transaction Calculation Error

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/LedgerSMB#963]
In 1.4.17

Purchases->Add Transaction

* Enter Amount £100.00
* Manually Enter £20.00 tax
* Click Update
* Note Total correctly shows £120.00 against Creditors Control Account
* Click Save

Total is now wrong - shows £140.00 instead of £120.00

**Comment by nick-prater** [comment]
Reversing commit b40562f27472547a61ec00d1365936afe9d9945d (Enable automatic calculation of taxes on AR/AP transactions) fixes this.

**Comment by nick-prater** [comment]
This is still broken in 1.4.18-rc1

I've tested automatic tax calculation and that is broken too:

* Purchases->Add Transaction
* Enter an amount
* Click Update
* Tick the 'automatically calculate' box for a tax line
* Click Update
* Note that the tax amount is filled-in automatically
* Click 'Save'

The tax amount is now reset to zero, whereas it should retain the automatically calculated amount.

**Comment by nick-prater** [comment]
Commit 8dfb9e980b6086defaae3553c1252e72f11f33c0 has improved matters, but this is still broken.

An automatically calculated tax amount is now retained after 'Save', but for both manual and automatic taxes the total is still wrong after clicking 'Save'.

Steps to reproduce:
* Purchases->Add Transaction
* Enter an amount
* Click Update
* Enter some tax
* Click Update
* Note the total is shown correctly
* Click Save
* Note the total is now wrong. Tax is being added twice.

**Comment by einhverfr** [comment]
There's a reason once we hit the RC process we almost always only fix fixes in the current release.  Otherwise there is the possibility of going down the road of having many rc's because there is insufficient time to really test a fix.  It is far better to do this during the normal development cycle rather than push in a fix after RC1 an then have several more RCs as we have dialog over the fix.

So at this point I don't really want to do more RC's.  I think I have a fix for this feature but if now, I will roll back the fixes for this issue and slate for 1.4.19.  Please test from 1.4 head and let me know if we need to go back to rc1 and document the feature with "don't use this yet."

**Comment by nick-prater** [comment]
Still broken I'm afraid. This is a tricky one.

To be clear, it isn't just new functionality that's broken. Entering tax manually is been broken too. So if we're going to document it, we're saying don't upgrade to recent versions of ledgersmb if you need to enter transactions with tax.

In my view, being able to enter a transaction is a core feature of ledgersmb, and releasing in the knowledge that such a core feature is broken seems wrong.

I'd prefer to revert the original commit that caused this problem  b40562f27472547a61ec00d1365936afe9d9945d before release, which can then be fixed and reapplied at leisure. That's what I've done to get my installation into a usable state, but I understand if you see things differently.

**Comment by einhverfr** [comment]
Does that make it all work even off current tip of 1.4 after Erik's changes yesterday?  We have made several fixes in this corner and it isn't clear one can just revertt one commit and have things work at present.

Please include a repro and observations here.  We can't even begin to evaluate without that.
Otherwise all we can go by is our testing, and with Erik's fix yesterday, the repros seem to be resolved.

**Comment by nick-prater** [comment]
I confirm this is fixed in 1.4.18-rc3.
Thanks for your work on this.
